DELETE FROM customer;
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES(1,'Revit','Hathaisatpong','342 Church St TASreet VIC','3000','0403872130','hrevit@gmail.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES(2,'Matthew','Smiths','3 Parkland Blv QLD','4010','0401233214','matthew@gmail.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (3,'Gustavo','Ponce','45 Harward St SA','5600','0403157130','test@test.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (4,'Bob','Marley','208 Adelaid St ACT','2090','0402321543','one@love.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (5,'David','Gilmour','250 Pitt St NSW','2260','0409456321','high@hopes.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (6,'John','Lennon','6 Kent st NSW','2000','0401872730','standby@me.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (7,'Ozzy','Osbourne','342 Church St SA','6750','0403872130','children@grave.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (8,'Jimmy','Page','342 Church St TAS','5400','0403872540','stairway@heaven.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (9,'Jimi','Hendrix','1/352 Broadway St NSW','2110','0406772130','purple@haze.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (10,'Sex','Pistols','33 Victoria St VIC','3320','0403872890','save@queen.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (11,'Jim','Morrison','431/1 Genroy Avenue St VIC','3130','0465756541','riders@storm.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (12,'Richard','Blackmore','1 View St TAS','6500','0408172130','highway@star.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (13,'Jay','Kay','31 Clarence St NT','7600','0404356130','cosmic@girl.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (14,'David','Bowie','3/1 Miller St TAS','7700','0403889130','heroes@oneday.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (15,'Bob','Dylan','89 Jones St NT','5600','0403876120','knocking@doors.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (16,'Manu','Chao','2/1 Edward AVenue QLD','3470','0403832120','mala@vida.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (17,'The','Specials','115 Cambridge St NSW','2600','0403872130','ghost@thown.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (18,'Jymmy','Cliff','41 Northcote St SA','3000','0403856430','see@clearly.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (19,'The','Temptations','111 Military St WA','6600','047654130','my@girl.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (20,'Simon','Garfunkel','54 King St VIC','3450','0405689130','mr@robinson.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (21,'Catch','Steven','31 Queen St TAS','3000','0403870980','takes@sometime.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (22,'Janis','Joplin','7/2 Northbourne St WA','6700','0403905130','cry@baby.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (23,'Lou','Red','90 University St NSW','8900','0401232130','wild@side.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (24,'Iggy','Pop','33 College St SA','3770','0407564130','the@passenger.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (25,'Dead','Kennedys','60 James St WA','4560','0403563230','holiday@cambodia.com');
INSERT INTO customer(customer_id,firstname,lastname,address,postal,phone,email) VALUES (26,'The','Cure','87 Brancroft St TAS','3120','0403877630','dont@cry.com');


DELETE FROM claim;
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(1,'A','Back Injured',1);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(2,'B','Heart Transplant',2);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(3,'C','Back Muscle Pain',3);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(4,'B','Boken Leg',4);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(5,'A','Heart Burn',5);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(6,'B','Botox',6);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(7,'B','Facelift',7);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(8,'C','Skin Cancer',8);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(9,'C','Pneumonia',9);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(10,'B','Quit Smoking',10);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(11,'D','Asthma',11);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(12,'B','Migrane',12);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(13,'C','Allegies',13);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(14,'B','Diabets',14);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(15,'B','Digestion',15);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(16,'A','Chronic Pain',16);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(17,'B','Clod and Flue',17);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(18,'C','Infectious Desease',18);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(19,'B','High Blood Presures',19);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(20,'A','Eyesight',20);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(21,'B','Heat Cramps',21);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(22,'A','Liver Blood Tests',22);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(23,'A','Abnominal Pain',23);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(24,'B','Abrasion',24);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(25,'B','Achiles Tendon Rupture',25);
INSERT INTO claim(claim_id,category,description,fk_customer_id) VALUES(26,'C','Steroid',26);